In [1]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn import datasets
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline

In [2]:
iris=datasets.load_iris()

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
X=iris.data
y=iris.target

In [5]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

## Gaussian Naive Bayes

### 主要用於連續變數，比方說特徵長度為幾公分、重量為幾公斤等等。

$$ P(X_j|Y_i)=\frac{1}{\sqrt{2\pi\sigma_{Y_i}^2}} exp(-\frac{(X_j-\mu_{Y_i})^2}{2\sigma_{Y_i}^{2}})$$

In [6]:
modelg=GaussianNB()
modelg.fit(X_train,y_train)
modelg.predict(X_test)

array([1, 0, 1, 0, 2, 1, 0, 1, 1, 2, 1, 2, 2, 1, 1, 2, 0, 0, 2, 0, 1, 1,
       1, 1, 2, 0, 2, 2, 2, 1, 2, 1, 2, 0, 0, 0, 2, 1, 1, 0, 2, 0, 2, 2,
       2])

In [7]:
modelg.predict_proba(X_test)

array([[3.77832030e-043, 1.00000000e+000, 4.21004935e-010],
       [1.00000000e+000, 1.10635060e-013, 1.96429811e-025],
       [3.12498254e-103, 9.99658771e-001, 3.41229198e-004],
       [1.00000000e+000, 4.79071949e-013, 1.39761525e-025],
       [4.79396961e-275, 4.53696303e-009, 9.99999995e-001],
       [1.52344146e-102, 9.99818515e-001, 1.81485105e-004],
       [1.00000000e+000, 5.34494525e-018, 4.08576979e-031],
       [1.67718052e-132, 7.38235178e-001, 2.61764822e-001],
       [9.09697801e-194, 8.81395643e-001, 1.18604357e-001],
       [7.26570071e-198, 6.91383349e-003, 9.93086167e-001],
       [3.02262491e-077, 9.99998976e-001, 1.02368519e-006],
       [9.56565931e-150, 3.70716958e-001, 6.29283042e-001],
       [1.75318751e-281, 7.85906833e-007, 9.99999214e-001],
       [1.72640435e-083, 9.99995535e-001, 4.46523845e-006],
       [4.73523745e-129, 9.98279466e-001, 1.72053369e-003],
       [1.02497988e-161, 1.64474325e-001, 8.35525675e-001],
       [1.00000000e+000, 2.53418482e-016

In [8]:
print('Training Set Score:',modelg.score(X_train,y_train))
print('Test Set Score:',modelg.score(X_test,y_test))

Training Set Score: 0.9714285714285714
Test Set Score: 0.9111111111111111


## Multinomial Naive Bayes

### 主要用在離散變數，比方說次數、類別等等。

 $$ P(Y_i)=\frac{N_{Y_i}+\alpha}{N+K_\alpha} $$
 $$ $$
 $$P(X_j|Y_i)=\frac{N_{Y_i,x_j}+\alpha}{N_{Y_i}+n\alpha} $$ 
 

In [9]:
modelm=MultinomialNB()
modelm.fit(X_train,y_train)
modelm.predict(X_test)

array([1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 2, 1, 1, 1, 2, 1, 1, 0, 0, 0, 2, 1, 1, 0, 1, 0, 1, 1,
       1])

In [10]:
modelm.predict_proba(X_test)

array([[0.11792256, 0.49956603, 0.3825114 ],
       [0.73632656, 0.17473812, 0.08893532],
       [0.07046044, 0.53069899, 0.39884057],
       [0.67352828, 0.21246053, 0.11401119],
       [0.00720884, 0.49644684, 0.49634433],
       [0.06776036, 0.52877593, 0.40346371],
       [0.78016847, 0.1462561 , 0.07357544],
       [0.06183214, 0.54031547, 0.39785239],
       [0.01859572, 0.52231887, 0.45908541],
       [0.01344029, 0.50859777, 0.47796193],
       [0.08471521, 0.51983021, 0.39545458],
       [0.04346882, 0.53857172, 0.41795947],
       [0.00974034, 0.52100651, 0.46925315],
       [0.05843291, 0.51325949, 0.4283076 ],
       [0.02101123, 0.49722877, 0.48176   ],
       [0.02340108, 0.5161151 , 0.46048382],
       [0.7219939 , 0.18216324, 0.09584286],
       [0.76654909, 0.15524497, 0.07820593],
       [0.01073335, 0.50010619, 0.48916047],
       [0.73095925, 0.17863761, 0.09040313],
       [0.07356497, 0.52000827, 0.40642676],
       [0.04839773, 0.53532838, 0.41627389],
       [0.

In [11]:
print('Training Set Score:',modelm.score(X_train,y_train))
print('Test Set Score:',modelm.score(X_test,y_test))

Training Set Score: 0.7619047619047619
Test Set Score: 0.6444444444444445


## Bernoulli Naive Bayes

### 用在二元的特徵，比方說特徵是否出現、特徵大小、特徵長短等等這種二元的分類。

$$ P(X_j|Y_i)=P_{Y_i}^{X_j}(1-P_{Y_i})^{X_j} $$

In [12]:
modelb = BernoulliNB()
modelb.fit(X_train,y_train)
modelb.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0])

In [24]:
modelb = BernoulliNB(binarize=1)
modelb.fit(X_train,y_train)
modelb.predict(X_test)

array([0, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 2,
       2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 2, 2, 2, 0, 2, 0, 2, 2,
       2])

In [25]:
modelb.score(X_test,y_test)

0.6888888888888889

In [26]:
X=pd.DataFrame(X)
X.describe()

0           1           2           3
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.057333    3.758000    1.199333
std      0.828066    0.435866    1.765298    0.762238
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [70]:
modelb = BernoulliNB(binarize=4.8)
modelb.fit(X_train,y_train)
modelb.predict(X_test)

array([1, 1, 1, 0, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 0, 1, 2, 1, 1, 1,
       1, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 0, 0, 1, 2, 1, 1, 1, 2, 1, 2, 2,
       2])

In [71]:
modelb.predict_proba(X_test)

array([[0.42394773, 0.53022878, 0.0458235 ],
       [0.42394773, 0.53022878, 0.0458235 ],
       [0.42394773, 0.53022878, 0.0458235 ],
       [0.92831499, 0.0651726 , 0.00651241],
       [0.02045297, 0.11736893, 0.8621781 ],
       [0.42394773, 0.53022878, 0.0458235 ],
       [0.42394773, 0.53022878, 0.0458235 ],
       [0.42394773, 0.53022878, 0.0458235 ],
       [0.02045297, 0.11736893, 0.8621781 ],
       [0.02045297, 0.11736893, 0.8621781 ],
       [0.42394773, 0.53022878, 0.0458235 ],
       [0.02045297, 0.11736893, 0.8621781 ],
       [0.02045297, 0.11736893, 0.8621781 ],
       [0.42394773, 0.53022878, 0.0458235 ],
       [0.42394773, 0.53022878, 0.0458235 ],
       [0.02045297, 0.11736893, 0.8621781 ],
       [0.92831499, 0.0651726 , 0.00651241],
       [0.42394773, 0.53022878, 0.0458235 ],
       [0.02045297, 0.11736893, 0.8621781 ],
       [0.42394773, 0.53022878, 0.0458235 ],
       [0.42394773, 0.53022878, 0.0458235 ],
       [0.42394773, 0.53022878, 0.0458235 ],
       [0.

In [72]:
print('Training Set Score:',modelb.score(X_train,y_train))
print('Test Set Score:',modelb.score(X_test,y_test))

Training Set Score: 0.7047619047619048
Test Set Score: 0.7777777777777778
